### ISSUE TITLE
NALU-wind failing in BELOS solvers for certain mesh stretchin ratio

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#590]
Hi NALU-wind team,

I am running a box type hexahedral mesh, with vertical mesh stretching. For some mesh stretching, the code fails on Belos solvers, while for some it does run without any issues. I am using a RANS wall-model, and stretching the mesh would mean smaller cell-sizes at the wall. However, I see the failure is occurring not because the cell-size at the wall is becoming smaller, but when the ratio of wall-cell size / top-BC cell size becomes larger than some threshold. 
[abl_preprocess.yaml.txt](https://github.com/Exawind/nalu-wind/files/4634922/abl_preprocess.yaml.txt)
[abl_simulation.yaml.txt](https://github.com/Exawind/nalu-wind/files/4634923/abl_simulation.yaml.txt)
[user_script.stderr.txt](https://github.com/Exawind/nalu-wind/files/4634929/user_script.stderr.txt)
[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/4634934/abl_simulation.log)

Physics-wise, this would not make sense, but 
numerically, I am not sure if the matrix-solver is somehow getting ill-conditioned because of this. 

For the nalu abl-mesh utility, that we have been using, 

```
 vertices:
  - [0.0, 0.0, 0.0]
  - [5000, 4000.0, 1000.0]

  mesh_dimensions: [167,134,100]


# Mesh-spacing for vertically refined mesh: mesh streching #
  x_spacing:
    spacing_type: constant_spacing

  y_spacing:
    spacing_type: constant_spacing

  z_spacing:
    spacing_type: geometric_stretching
    stretching_factor: 1.045

```

Interestingly, if we change the mesh-stretching ~ 1.0075, and the vertical cell-counts to 400 from 100, the case runs. it means the wall-cell size is smaller than the current setting, but the top -cell size/ wall cell-size is now smaller. CFL, changing the preconditioners do not help here.

Any suggestions as to why this is happening. 
nalu log files and stderr files and (preprocess, simulation yaml) file is attached below.

**Comment by sayerhs** [comment]
@tchatte3 Assuming you're running with `master` branch of `nalu-wind`, this looks suspect 

```
    - wall_boundary_condition: bc_bot
      target_name: lower
      wall_user_data:
        velocity: [0,0,0]
        turbulent_ke: 1.0875
#        specific_dissipation_rate: 0.25059
        use_wall_function: yes
```

This BC should be set similar to what is used for the wall boundary in `airfoilRANSEdge` regression test case. Specifically, I'd start with `use_wall_function: no`

**Comment by tchatte3** [comment]
@sayerhs . Thanks. I have turned on/off wall-function, various values of turbulent_ke. (even from the airfoilRANSedge regression suite. .e., 0 velocity, tke), but the code still fails at the first time step with the BELOS solver throwing error, as reported earlier. That makes me suspect, it is solely a mesh issue.

I will look further ...

**Comment by sayerhs** [comment]
I would recommend visualizing the mesh and the wall distance field that is being computed.

**Comment by tchatte3** [comment]
![image](https://user-images.githubusercontent.com/14302216/82083754-3bd22c80-96b8-11ea-96ff-4a17a6464563.png)

![image](https://user-images.githubusercontent.com/14302216/82084083-c1ee7300-96b8-11ea-9e90-f33f58f87f6a.png)

The wall-cell size ~ 0.5 metres and top cell ~ 43 metres (100 cell count, stretching ratio =1.045), as I set-up in the nalu abl mesh yaml script, through a stretching ratio. So, that's that in terms of sanity check. The mesh does not look different from its sister mesh (cell count = 100, stretching ratio  = 1.035), where the wall cell-size ~ 1.15 metres,  ~ 37 metres. The sister mesh runs fine with the abl_simulation.yaml input file. For the mesh which runs, I see from post-processing of wall-forces that y+ ~ 7000 (based on effective_viscosity_u), so I would assume a same ball-park value of y+ (~ O(10^4) ) for the mesh which does not run. Of course, there is no way to know, since for that mesh, the solver fails at first time-step. the post-processing data files are not yet populated.

**Comment by sayerhs** [comment]
@tchatte3 You are solving a Poisson equation to compute the nearest distance to wall that is used by other transport equations. 

```
 1/1         myNDTW
        WallDistEQS            8           43.9381        13121.7             1
Realm shall provide output files at : currentTime/timeStepCount: 0/0 (fluidRealm)
Realm shall provide restart files at: currentTime/timeStepCount: 0/0 (fluidRealm)
```

This equation is solved before starting timestep loop, and is output in the zeroth timestep. The field is called `minimum_distance_to_wall`, can you plot that field and see if there are issues with that? 

Beyond this, to debug the problem, you'll want to do start changing the configuration to narrow down which term is causing the problem. I'd start by removing the ABL terms and running a simple channel flow, removing periodic and doing a simple inflow/outflow, etc. to understand what is causing NaNs. Given that you are initializing the flowfield with uniform inflow, it is a little weird that the first momentum solve would crash.

**Comment by tchatte3** [comment]
@sayerhs Good point. I will definitely check this.

**Comment by tchatte3** [comment]
@sayerhs , I was able to make these meshes run with inflow/outflow case . The same mesh failed in periodic simulation case. Incidentally, the cases were the mesh failed: NDTW system (the poisson solver) residual was always pretty high. I am not sure if this tells that for periodic simulations, the linear solvers [Ax = b], the matrix is really bad/ill-conditioned somehow? Any suggestions to overcome this problem?

**Comment by sayerhs** [comment]
- Wall distance computation is a Poisson solve that uses Neumann BCs everywhere except the wall where it is set to Dirichlet. As far as the linear system is concerned, it wouldn't see a difference between inlet/outlet and periodic BCs. 

- Have you visualized the `min_distance_to_wall` field that is output to the exodus file? https://github.com/Exawind/nalu-wind/issues/590#issuecomment-629418770 only visualizes the mesh and not the wall distance field that is computed by the equation. 

- Can you try tightening the `search_tolerance` for the periodic boundary conditions and see if that improves matters?

**Comment by tchatte3** [comment]
@sayerhs . Thanks for the inputs. Yes, I did check the minimum_distance_to_wall at timestep 0. Since, at timestep 1, nothing is dumped, the solver crashes. I don't find anything suspicious.
My min dist. to wall should go from 0 to 1000 at time-zero, and that is what is happenning.

I tried tighening the tolerance for the search algorithm in periodic BC to 1e-10, even. The solution still fails, and that the zeroth time-step, the residuals of the NDTW solve is only slightly better.  But the BELOS solver still throws error.

<img width="331" alt="minimum_distance_to_wall" src="https://user-images.githubusercontent.com/14302216/82335393-3fff9200-99b7-11ea-930d-2203c70d6f21.PNG">
<img width="333" alt="NDTW_zoom" src="https://user-images.githubusercontent.com/14302216/82335398-41c95580-99b7-11ea-9f50-8a1f9b18fc3e.PNG">

**Comment by tchatte3** [comment]
@sayerhs , Thanks for the inputs. I am closing the issue now. I think, I found a work-around solution. I see that when my mesh-stretching ratio is of the form 1.XXX5, this problem happens. If I make my stretching ratio 1.XXX5 + eps, where eps is a small number (carefully chosen), I am able to work-around this issue. So, in such cases the BELOS solver errors are not thrown and the NDTW equation system at 0th timestep converges. Seems like a floating point arithmetic issue.
